version: '3.8'

services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "blog-api:latest"
    container_name: blog-api
    volumes:
      - /root/blog/images:/home/app/images
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=blog
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    volumes:
    - ~/postgres/data:/var/lib/postgresql/data